In [239]:
# imports
import pandas as pd
import numpy as np
import sys
sys.path.append("../../src")

from point_deduplicator import process_data

In [240]:
# USER CONFIGURATION 
# change these paths

DATA_PATH = "spatial_distance_search.csv"
MAPPING_PATH = "tammireitit_lipas_type_mapping.csv"

df = pd.read_csv(DATA_PATH)
mapping_df = pd.read_csv(MAPPING_PATH, sep=";")

print("Data preview:")
display(df.head())

print("Mapping preview:")
display(mapping_df.head())

print("\nColumns:")
print(df.columns.tolist())

Data preview:

,fid,omistaja,yllapitaja,tyyppi,lisatieto,kunta,reitti,kohde,sijainti,palvelut,...,lipas_id,lipas_tyyppikoodi,lipas_tyyppi_nimi_fi,lipas_nimi_fi,n,distance,feature_x,feature_y,nearest_x,nearest_y
0,1,Muu,Yksityinen / yhdistys,Pysakointi_liikeste,NaN,Kaarina,Tuorlan esteetön luontopolku,Pysäköintialue,Avaruuspuisto Väisälä,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,NaN,NaN,Luontotorni,NaN,Lieto,Nautelankosken luonnonsuojelualueen polut / Au...,Näkötorni,Nautelankoski,NaN,...,610047.0,204.0,Luontotorni,Nautelan lintutorni,1.0,11.208168,251156.558739,6.721945e+06,251147.2793,6721939.009
2,3,NaN,NaN,Taukopaikka,NaN,Lieto,Ankka-Nautela luontopolku,Taukopaikka,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,NaN,NaN,Portaat,NaN,Lieto,Vanhalinnan Ystävänpolku,Portaat,Vanhalinna,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,NaN,NaN,Tulipaikka,NaN,Lieto,Ankka-Nautela luontopolku,Laavu,Liesan maja,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Mapping preview:

,id,tammireitti_tyyppi,lipas_type_name,lipas_type_code,confirmed,lipas_loi_type
0,1,Pysakointi_liikeste,NaN,NaN,False,parking-spot
1,2,Luontotorni,Luontotorni,204.0,False,NaN
2,3,Taukopaikka,NaN,NaN,False,rest-area
3,4,Portaat,NaN,NaN,False,stairs
4,5,Tulipaikka,NaN,NaN,False,fire-pit

Columns:
['fid', 'omistaja', 'yllapitaja', 'tyyppi', 'lisatieto', 'kunta', 'reitti', 'kohde', 'sijainti', 'palvelut', 'linkki', 'rotate', 'source_id', 'lipas_id', 'lipas_tyyppikoodi', 'lipas_tyyppi_nimi_fi', 'lipas_nimi_fi', 'n', 'distance', 'feature_x', 'feature_y', 'nearest_x', 'nearest_y']

In [241]:
# USER CONFIGURATION
# Add here your column names

ID_COL = "source_id"
LIPAS_ID_COL = "lipas_id"
CLASS_COL = "tyyppi"
TYPE_COL_LIPAS = "lipas_tyyppi_nimi_fi"

MAP_KEY = "tammireitti_tyyppi"
MAP_VALUE = "lipas_type_name"

NAME1_COL = "kohde"
NAME2_COL = "lipas_nimi_fi"

# Optional
DISTANCE = "distance"

In [242]:
true_matches, true_matches_duplicates, mismatches, review_mismatches_duplicates, needs_checking, not_matched = process_data(
    df,
    mapping_df,
    id_col=ID_COL,
    lipas_id_col=LIPAS_ID_COL,
    class_col=CLASS_COL,
    type_col=TYPE_COL_LIPAS,
    map_key=MAP_KEY,
    map_value=MAP_VALUE,
    name1_col=NAME1_COL,
    name2_col=NAME2_COL
)

found true matches so far (20, 25)
found true matches so far (29, 25)
true_matches: (36, 25)
true_matches duplicates: (4, 25)
mismatches: (6, 25)
needs_checking: (171, 25)
mismatches_duplicates: (14, 25)
no matches found: (205, 23)
Total unique entries: 347

C:\Users\ronit\Nextcloud2\Opiskelu\Digiretki\digiretki_to_lipas-main\digiretki_to_lipas-main\notebooks\point_deduplicator\../../src\point_deduplicator.py:188: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  true_matches = pd.concat([true_matches, matches_in_true_duplicates], ignore_index=True)
C:\Users\ronit\Nextcloud2\Opiskelu\Digiretki\digiretki_to_lipas-main\digiretki_to_lipas-main\notebooks\point_deduplicator\../../src\point_deduplicator.py:189: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  true_matches = pd.concat([true_matches, matches_in_duplicate_mismatches], ignore_index=True)

In [243]:
# Review that the results are correct

true_matches.loc[:, [ID_COL, LIPAS_ID_COL, CLASS_COL, TYPE_COL_LIPAS, NAME1_COL, NAME2_COL, DISTANCE]]

,source_id,lipas_id,tyyppi,lipas_tyyppi_nimi_fi,kohde,lipas_nimi_fi,distance
0,74,513259.0,Tulipaikka,Uimaranta,Hiekkahelmi,Hiekkahelmi,30.210651
1,75,513259.0,Kuivakaymala,Uimaranta,Hiekkahelmi,Hiekkahelmi,42.065723
2,77,513259.0,Pysakointi_liikeste,Uimaranta,Hiekkahelmi,Hiekkahelmi,67.396059
3,95,100120.0,Uimaranta,Uimaranta,Ankkalammen maauimala,Oinilan maauimala,111.977824
4,109,513259.0,Uimaranta,Uimaranta,Hiekkahelmi,Hiekkahelmi,4.346709
5,144,99224.0,Uimaranta,Uimaranta,Hovirinnan uimaranta,Hovirinnan uimaranta,39.527266
6,164,99453.0,Vesillelasku,Uimapaikka,Ristikallion uimaranta,Ristikallion uimaranta,6.544736
7,165,99000.0,Rantautuminen,Uimaranta,Littoisten uimaranta,Littoisten uimaranta,85.227887
8,166,99224.0,Vesillelasku,Uimaranta,Hovirinnan uimaranta,Hovirinnan uimaranta,85.291733
9,177,99453.0,Pysakointialue,Uimapaikka,Ristikallion uimaranta,Ristikallion uimaranta,49.529851
10,230,511821.0,Opastaulu,Jalkapallohalli,Peimari-Areena,Peimari-Areena,69.054052
11,298,98730.0,Uimaranta,Uimaranta,Harvaluodon uimaranta,Harvaluodon uimaranta,19.061482
12,304,99224.0,Rantautuminen,Uimaranta,Hovirinnan uimaranta,Hovirinnan uimaranta,96.785596
13,308,99453.0,Rantautuminen,Uimapaikka,Ristikallion uimaranta,Ristikallion uimaranta,19.713311
14,47,611084.0,Vesillelasku,Veneilyn palvelupaikka,Järvelän esteetön melontalaituri,Littoistenjärven esteetön melontalaituri,6.196209
15,127,506993.0,Opastaulu,Frisbeegolfrata,Paimio Disc Golf Park,Paimio DiscGolfPark,43.378777
16,129,91856.0,Nahtavyys,Hyppyrimäki,Varasvuoren hyppyrimäet,Varasvuoren hyppyrimäki K58,12.816658
17,228,99224.0,Opastaulu,Uimaranta,Hovirinnan rantapuisto,Hovirinnan uimaranta,139.734996
18,240,99000.0,Opastaulu,Uimaranta,Littoistenjärven uimaranta,Littoisten uimaranta,62.535924
19,272,84136.0,Pysakointialue,Pallokenttä,Piispanlähteen yläkoulu,Piispanlähteen yläkoulun pallokenttä,75.074959
20,2,610047.0,Luontotorni,Luontotorni,Näkötorni,Nautelan lintutorni,11.208168
21,147,513704.0,Uimaranta,Uimaranta,Voivalan uimaranta,Voivalan uimaranta,172.050679
22,162,606718.0,Luontotorni,Luontotorni,Kuusistonlahden lintutorni pohjoinen,Kuusistonlahden lintutorni (pohjoinen),0.793913
23,163,616714.0,Luontotorni,Luontotorni,Piikkiönlahden lintutorni,Piikkiönlahden esteetön lintutorni,2.678285
24,172,513704.0,Rantautuminen,Uimaranta,Voivalan uimaranta,Voivalan uimaranta,175.549668
25,216,606722.0,Luontotorni,Luontotorni,Vaarniemen näkötorni,Vaarniemen näkötorni,0.878038
26,249,99546.0,Uimaranta,Uimaranta,Rantolan uimaranta,Rantolan uimaranta,9.118487
27,276,606720.0,Luontotorni,Luontotorni,Rauvolan lintutorni,Rauvolanlahden lintutorni,7.791347
28,311,606723.0,Luontotorni,Luontotorni,Järvelän kosteikko,Järvelän lintulava,2.141423
29,156,513706.0,Uimaranta,Uimapaikka,Raadelman uimaranta,Raadelman uimapaikka,18.733662
30,167,100089.0,Rantautuminen,Uimapaikka,Kuuslahden uimapaikka,Kuuslahden uimaranta,26.994063
31,171,513706.0,Rantautuminen,Uimapaikka,Raadelman uimaranta,Raadelman uimapaikka,7.896031
32,297,100089.0,Uimaranta,Uimapaikka,Kuuslahden uimapaikka,Kuuslahden uimaranta,11.899998
33,173,614559.0,Vesillelasku,Kalastuskohde (piste),Harvaluodon silta,Harvaluodon sillanpieli,47.065495
34,296,100089.0,Pysakointialue,Uimapaikka,Kuuslahden uimapaikka,Kuuslahden uimaranta,105.465292
35,305,100089.0,Tulipaikka,Uimapaikka,Kuuslahden uimapaikka,Kuuslahden uimaranta,22.903846

In [244]:
# Manipulate results example
# Row indexes that should NOT be true matches

# Row indexes to be moved
row_idxs_to_move = [0, 1, 2, 6, 7, 8, 9, 10, 12, 13, 15, 17, 18, 19, 24, 30, 31, 33, 34, 35]

# Get the rows from the original dataframe
rows_to_move = true_matches.loc[row_idxs_to_move]

# Concatenate the rows to the correct dataframe
mismatches = pd.concat([mismatches, rows_to_move], ignore_index=True)

# Drop rows from the original dataframe
true_matches = true_matches.drop(index=row_idxs_to_move)

In [245]:
# Review duplicate true_matches

true_matches_duplicates.loc[:, [ID_COL, LIPAS_ID_COL, CLASS_COL, TYPE_COL_LIPAS, NAME1_COL, NAME2_COL, DISTANCE]]

,source_id,lipas_id,tyyppi,lipas_tyyppi_nimi_fi,kohde,lipas_nimi_fi,distance
0,7,611083.0,Luontotorni,Luontotorni,Lintutorni,Järvelän näköala- ja lintutorni,3.222886
1,7,606725.0,Luontotorni,Luontotorni,Lintutorni,Littoistenjärven lintutorni,139.553462
2,310,606725.0,Luontotorni,Luontotorni,NaN,Littoistenjärven lintutorni,0.726086
3,310,611083.0,Luontotorni,Luontotorni,NaN,Järvelän näköala- ja lintutorni,138.330965

In [246]:
# Select the correct match from the candidates that have duplicate options

# Row indexes to be moved
row_idxs_to_true = [0, 2] 

# Get the rows from the original dataframe
rows_to_move = true_matches_duplicates.loc[row_idxs_to_true]

# Concatenate the rows to the correct dataframe
true_matches = pd.concat([true_matches, rows_to_move], ignore_index=True)

# Drop from the original dataframe
true_matches_duplicates = true_matches_duplicates.drop(index=row_idxs_to_true)

In [247]:
# Review mismatched entries
mismatches.loc[:, [ID_COL, CLASS_COL, TYPE_COL_LIPAS, NAME1_COL, NAME2_COL, DISTANCE]]

,source_id,tyyppi,lipas_tyyppi_nimi_fi,kohde,lipas_nimi_fi,distance
0,168,Rantautuminen,Talviuintipaikka,Villa Wolax,Villa Wolaxin talviuintipaikka,49.100556
1,180,Rantautuminen,Kalastuskohde (piste),Oleskelulaituri,Kuusiston sillanpieli,199.048595
2,186,Rantautuminen,Uimapaikka,Sarapisto,Sarapiston uimapaikka,40.188465
3,284,Uimaranta,Uimapaikka,Sarapisto,Sarapiston uimapaikka,25.943685
4,293,Laavu,Luontotorni,NaN,Vaarniemen näkötorni,70.312319
5,338,Rantautuminen,Luontotorni,NaN,Nautelan lintutorni,63.783284
6,74,Tulipaikka,Uimaranta,Hiekkahelmi,Hiekkahelmi,30.210651
7,75,Kuivakaymala,Uimaranta,Hiekkahelmi,Hiekkahelmi,42.065723
8,77,Pysakointi_liikeste,Uimaranta,Hiekkahelmi,Hiekkahelmi,67.396059
9,164,Vesillelasku,Uimapaikka,Ristikallion uimaranta,Ristikallion uimaranta,6.544736
10,165,Rantautuminen,Uimaranta,Littoisten uimaranta,Littoisten uimaranta,85.227887
11,166,Vesillelasku,Uimaranta,Hovirinnan uimaranta,Hovirinnan uimaranta,85.291733
12,177,Pysakointialue,Uimapaikka,Ristikallion uimaranta,Ristikallion uimaranta,49.529851
13,230,Opastaulu,Jalkapallohalli,Peimari-Areena,Peimari-Areena,69.054052
14,304,Rantautuminen,Uimaranta,Hovirinnan uimaranta,Hovirinnan uimaranta,96.785596
15,308,Rantautuminen,Uimapaikka,Ristikallion uimaranta,Ristikallion uimaranta,19.713311
16,127,Opastaulu,Frisbeegolfrata,Paimio Disc Golf Park,Paimio DiscGolfPark,43.378777
17,228,Opastaulu,Uimaranta,Hovirinnan rantapuisto,Hovirinnan uimaranta,139.734996
18,240,Opastaulu,Uimaranta,Littoistenjärven uimaranta,Littoisten uimaranta,62.535924
19,272,Pysakointialue,Pallokenttä,Piispanlähteen yläkoulu,Piispanlähteen yläkoulun pallokenttä,75.074959
20,172,Rantautuminen,Uimaranta,Voivalan uimaranta,Voivalan uimaranta,175.549668
21,167,Rantautuminen,Uimapaikka,Kuuslahden uimapaikka,Kuuslahden uimaranta,26.994063
22,171,Rantautuminen,Uimapaikka,Raadelman uimaranta,Raadelman uimapaikka,7.896031
23,173,Vesillelasku,Kalastuskohde (piste),Harvaluodon silta,Harvaluodon sillanpieli,47.065495
24,296,Pysakointialue,Uimapaikka,Kuuslahden uimapaikka,Kuuslahden uimaranta,105.465292
25,305,Tulipaikka,Uimapaikka,Kuuslahden uimapaikka,Kuuslahden uimaranta,22.903846

In [248]:
# Source IDs that should be moved from mismatches to true matches
ids_to_move = [284]

move_mask = mismatches[ID_COL].isin(ids_to_move)

# Move them to true_matches
true_matches = pd.concat(
    [true_matches, mismatches.loc[move_mask]],
    ignore_index=True
)

# Remove them from mismatches
mismatches = mismatches.loc[~move_mask].copy()

In [249]:
# Review mismatched duplicate entries

review_mismatches_duplicates.loc[:, [ID_COL, CLASS_COL, TYPE_COL_LIPAS, NAME1_COL, NAME2_COL]]

,source_id,tyyppi,lipas_tyyppi_nimi_fi,kohde,lipas_nimi_fi
0,50,Rantautuminen,Ulkokuntoilupaikka,NaN,Jokipuiston kuntoportaat
1,50,Rantautuminen,Ulkokuntoilupaikka,NaN,Villen kuntokeidas
2,130,Infopiste,Liikuntasali,Kaupungintalo ja kirjasto,Koulukeskuksen liikuntasali 2
3,130,Infopiste,Lähiliikuntapaikka,Kaupungintalo ja kirjasto,Paimion koulukeskuksen lähiliikuntapaikka
4,130,Infopiste,Kuntosali,Kaupungintalo ja kirjasto,Paimion uimahallin kuntosali Kolina
5,175,Rantautuminen,Uimaranta,Harvaluodon virkistysalue,Harvaluodon uimaranta
6,175,Rantautuminen,Ulkokuntoilupaikka,Harvaluodon virkistysalue,Harvaluodon rannan ulkokuntoilulaite
7,175,Rantautuminen,Frisbeegolfrata,Harvaluodon virkistysalue,Harvaluodon frisbeegolfrata
8,185,Rantautuminen,Uimapaikka,Marjaniemen leirikeskus,Marjaniemen uimaranta ja sauna
9,185,Rantautuminen,Frisbeegolfrata,Marjaniemen leirikeskus,Marjaniemi DiscGolfPark
10,187,Rantautuminen,Talviuintipaikka,Karunan Kallioranta,Kalliorannan talviuintipaikka
11,187,Rantautuminen,Pallokenttä,Karunan Kallioranta,Karunan jalkapallokenttä
12,283,Uimaranta,Uimapaikka,Marjaniemi,Marjaniemen uimaranta ja sauna
13,283,Uimaranta,Frisbeegolfrata,Marjaniemi,Marjaniemi DiscGolfPark

In [250]:
# Move a mismatch with duplicates to true match

# Row indexes to be moved
row_idxs_to_true = [12] 

# Get the rows from the original dataframe
rows_to_move = review_mismatches_duplicates.loc[row_idxs_to_true]

# Concatenate the rows to the correct dataframe
true_matches = pd.concat([true_matches, rows_to_move], ignore_index=True)

# Drop from the original dataframe
review_mismatches_duplicates = review_mismatches_duplicates.drop(index=row_idxs_to_true)

In [251]:
# Review results that need a manual check
with pd.option_context("display.max_rows", None):
    display(needs_checking.loc[:,[ID_COL, CLASS_COL, TYPE_COL_LIPAS, NAME1_COL, NAME2_COL, DISTANCE]])

,source_id,tyyppi,lipas_tyyppi_nimi_fi,kohde,lipas_nimi_fi,distance
0,14,Pysakointialue,Beachvolley-/rantalentopallokenttä,Pysäköintialue,Järvelän beachvolleykenttä 1,36.620623
1,14,Pysakointialue,Beachvolley-/rantalentopallokenttä,Pysäköintialue,Järvelän beachvolleykenttä 2,46.642166
2,14,Pysakointialue,Uimapaikka,Pysäköintialue,Järvelän uimapaikka,64.157156
3,16,Pysakointialue,Ulkokuntoilupaikka,Pysäköintialue,Kaupungintalon ulkokuntosali,69.159953
4,16,Pysakointialue,Koripallokenttä,Pysäköintialue,Laurin kentän koripalloalue,111.762759
5,16,Pysakointialue,Luistelukenttä,Pysäköintialue,Laurin luistelukenttä,154.596821
6,22,Opastaulu,Uimapaikka,Tammireittien opastaulu,Järvelän uimapaikka,33.717029
7,22,Opastaulu,Veneilyn palvelupaikka,Tammireittien opastaulu,Littoistenjärven esteetön melontalaituri,45.994990
8,22,Opastaulu,Beachvolley-/rantalentopallokenttä,Tammireittien opastaulu,Järvelän beachvolleykenttä 1,74.990041
9,31,Nahtavyys,"Laavu, kota tai kammi",Saukonojan vanha koulu,Saukonojan kyläyhdistyksen laavu,44.942541
10,31,Nahtavyys,Ulkokuntoilupaikka,Saukonojan vanha koulu,Saukonojan kuntoportaat,57.267868
11,31,Nahtavyys,Luistelukenttä,Saukonojan vanha koulu,Saukonojan luistelukenttä,79.554828
12,38,Nahtavyys,Pulkkamäki,Parmaharju,Parmaharjun pulkkamäki,65.515929
13,38,Nahtavyys,Kuntosali,Parmaharju,Parmaharjun kuntosali,102.965592
14,49,Vesillelasku,Ulkokuntoilupaikka,NaN,Jokipuiston kuntoportaat,133.633660
15,49,Vesillelasku,Ulkokuntoilupaikka,NaN,Villen kuntokeidas,152.095536
16,76,Pysakointialue,Uimaranta,NaN,Hiekkahelmi,103.160220
17,76,Pysakointialue,Beachvolley-/rantalentopallokenttä,NaN,Hiekkahelmen beachvolleykenttä,103.354784
18,82,Nakoala,Liikuntasali,Näkymä Paimionjoelle Isosillalta,Jokelan koulun liikuntasali,111.628890
19,82,Nakoala,Pallokenttä,Näkymä Paimionjoelle Isosillalta,Paimion Jokelan koulun pallokenttä,132.476307
20,82,Nakoala,Luistelukenttä,Näkymä Paimionjoelle Isosillalta,Jokelan koulun luistelukenttä,134.691014
21,83,Silta,Liikuntasali,Isosilta,Jokelan koulun liikuntasali,82.317281
22,83,Silta,Pallokenttä,Isosilta,Paimion Jokelan koulun pallokenttä,107.082487
23,83,Silta,Luistelukenttä,Isosilta,Jokelan koulun luistelukenttä,108.948143
24,84,Nakoala,Padelkenttä,Postinkujan idyllinen asuinalue,Padel Jokipuisto / Puisto-kenttä,126.573261
25,84,Nakoala,Padelkenttä,Postinkujan idyllinen asuinalue,Padel Jokipuisto / Joki-kenttä,132.915351
26,84,Nakoala,Luistelukenttä,Postinkujan idyllinen asuinalue,Jokelan koulun luistelukenttä,150.260665
27,86,Opastaulu,Ulkokuntoilupaikka,Jokipuisto,Jokipuiston kuntoportaat,55.346016
28,86,Opastaulu,Ulkokuntoilupaikka,Jokipuisto,Villen kuntokeidas,80.359554
29,86,Opastaulu,Padelkenttä,Jokipuisto,Padel Jokipuisto / Joki-kenttä,149.802135
30,90,Pysakointialue,Ulkokuntoilupaikka,Jokipuisto,Jokipuiston kuntoportaat,65.620512
31,90,Pysakointialue,Ulkokuntoilupaikka,Jokipuisto,Villen kuntokeidas,83.376845
32,90,Pysakointialue,Padelkenttä,Jokipuisto,Padel Jokipuisto / Joki-kenttä,171.851770
33,97,Pysakointialue,Uimaranta,Ankkalammen maauimala,Oinilan maauimala,129.399018
34,97,Pysakointialue,Ulkokuntoilupaikka,Ankkalammen maauimala,Oinilan ulkokuntosali,167.790217
35,98,Kuivakaymala,Uimaranta,Ankkalammen maauimala,Oinilan maauimala,144.172831
36,98,Kuivakaymala,Luistelukenttä,Ankkalammen maauimala,Oinilan kenttä,172.166199
37,98,Kuivakaymala,Pallokenttä,Ankkalammen maauimala,Oinilan hiekkakenttä,172.797808
38,99,Tulipaikka,Ulkokuntoilupaikka,Jokipuisto,Jokipuiston kuntoportaat,149.053235
39,99,Tulipaikka,Ulkokuntoilupaikka,Jokipuisto,Villen kuntokeidas,163.350106
40,105,Nahtavyys,Ulkokuntoilupaikka,Paimion Jokipuisto,Jokipuiston kuntoportaat,61.824911
41,105,Nahtavyys,Ulkokuntoilupaikka,Paimion Jokipuisto,Villen kuntokeidas,82.820098
42,105,Nahtavyys,Padelkenttä,Paimion Jokipuisto,Padel Jokipuisto / Joki-kenttä,163.029891
43,106,Kuivakaymala,Ulkokuntoilupaikka,Jokipuistp,Jokipuiston kuntoportaat,26.330621
44,106,Kuivakaymala,Ulkokuntoilupaikka,Jokipuistp,Villen kuntokeidas,44.806313
45,106,Kuivakaymala,Padelkenttä,Jokipuistp,Padel Jokipuisto / Joki-kenttä,106.827690
46,108,Opastaulu,Beachvolley-/rantalentopallokenttä,NaN,Hiekkahelmen beachvolleykenttä,77.842225
47,108,Opastaulu,Uimaranta,NaN,Hiekkahelmi,83.762245
48,116,Kahvila,Liikuntasali,Tadim kebab & pizzeria,Koulukeskuksen liikuntasali 2,58.268103
49,116,Kahvila,Lähiliikuntapaikka,Tadim kebab & pizzeria,Paimion koulukeskuksen lähiliikuntapaikka,91.627625
50,116,Kahvila,Kuntokeskus,Tadim kebab & pizzeria,Voimakas Sali,102.620494
51,118,Opastaulu,Pallokenttä,Urheilupuisto,Paimion urheilupuiston pallokenttä,32.531344
52,118,Opastaulu,Luistelukenttä,Urheilupuisto,Urheilupuiston luistelualue,34.586848
53,118,Opastaulu,Tenniskenttä,Urheilupuisto,Paimion urheilupuiston tenniskenttä 2,81.251275
54,124,Nahtavyys,Pallokenttä,Sukselan vanha kyläkoulu ja Sukselan nurmikenttä,Sukselan nurmikenttä,84.177984
55,124,Nahtavyys,Lentopallokenttä,Sukselan vanha kyläkoulu ja Sukselan nurmikenttä,Sukselan lentopallokenttä,123.391816
56,134,Nahtavyys,Kuntosali,"Paimion kirkko, eli Pyhän Mikaelin kirkko",Paimion uimahallin kuntosali Kolina,74.087930
57,134,Nahtavyys,Liikuntasali,"Paimion kirkko, eli Pyhän Mikaelin kirkko",Koulukeskuksen liikuntasali 3,92.395755
58,134,Nahtavyys,Liikuntasali,"Paimion kirkko, eli Pyhän Mikaelin kirkko",Koulukeskuksen liikuntasali 1,106.445886
59,140,Pysakointialue,Liikuntasali,NaN,Auranlaakson koulun liikuntasali,60.241253
60,140,Pysakointialue,Lähiliikuntapaikka,NaN,Auranlaakson koulun lähiliikuntapaikka,77.868673
61,140,Pysakointialue,Pallokenttä,NaN,Auranlaakson koulun pallokenttä,86.413025
62,142,Pysakointialue,Uimaranta,Hovirinnan uimarannan pysäköintialue,Hovirinnan uimaranta,53.970078
63,142,Pysakointialue,Talviuintipaikka,Hovirinnan uimarannan pysäköintialue,Hovirinnan talviuintipaikka,54.140584
64,142,Pysakointialue,Koripallokenttä,Hovirinnan uimarannan pysäköintialue,Hovirinnan rannan koripallokenttä,57.922778
65,176,Pysakointialue,Uimaranta,Littoistenjärven uimarannan pysäköintialue,Littoisten uimaranta,130.613122
66,176,Pysakointialue,Ulkokuntoilupaikka,Littoistenjärven uimarannan pysäköintialue,Littoisten uimarannan ulkokuntoilulaitteet,195.794318
67,178,Pysakointialue,Frisbeegolfrata,Harvaluodon virkistysalue,Harvaluodon frisbeegolfrata,31.326063
68,178,Pysakointialue,Ulkokuntoilupaikka,Harvaluodon virkistysalue,Harvaluodon rannan ulkokuntoilulaite,72.567407
69,178,Pysakointialue,Uimaranta,Harvaluodon virkistysalue,Harvaluodon uimaranta,81.048995
70,184,Pysakointialue,Talviuintipaikka,Karunan kalliorannan pysäköintialue,Kalliorannan talviuintipaikka,152.791107
71,184,Pysakointialue,Pallokenttä,Karunan kalliorannan pysäköintialue,Karunan jalkapallokenttä,193.534432
72,196,Nahtavyys,Ulkokuntoilupaikka,Sauvon kirjasto,Koulukeskuksen ulkokuntoilusali,125.161028
73,196,Nahtavyys,Lähiliikuntapaikka,Sauvon kirjasto,Koulukeskuksen lähiliikuntapaikka,127.633964
74,196,Nahtavyys,Lähiliikuntapaikka,Sauvon kirjasto,Palvelukeskuksen lähiliikuntapaikka,139.838937
75,197,Nahtavyys,Lähiliikuntapaikka,1930 -luvun funkkistalo,Palvelukeskuksen lähiliikuntapaikka,157.331011
76,197,Nahtavyys,Lähiliikuntapaikka,1930 -luvun funkkistalo,Koulukeskuksen lähiliikuntapaikka,181.083251
77,197,Nahtavyys,Ulkokuntoilupaikka,1930 -luvun funkkistalo,Koulukeskuksen ulkokuntoilusali,185.171642
78,219,Opastaulu,Ulkokuntoilupaikka,Pontelan yhdysreitti,Pontelan ulkokuntosali,70.045264
79,219,Opastaulu,Kuntosali,Pontelan yhdysreitti,Pontelan punttisali,106.144148
80,225,Opastaulu,Liikuntasali,"Kuusiston koulupolku, Empon koulu",Empolan sali,69.829408
81,225,Opastaulu,Luistelukenttä,"Kuusiston koulupolku, Empon koulu",Empon luistelukenttä,71.788167
82,225,Opastaulu,Pallokenttä,"Kuusiston koulupolku, Empon koulu",Empon pallokenttä,80.757941
83,226,Opastaulu,Luistelukenttä,"Kuusiston koulupolku, Kuusiston koulu",Kuusiston koulun luistelukenttä,38.656099
84,226,Opastaulu,Ulkokuntoilupaikka,"Kuusiston koulupolku, Kuusiston koulu",Kuusiston koulun ulkokuntoilulaitteet,41.996474
85,226,Opastaulu,Pallokenttä,"Kuusiston koulupolku, Kuusiston koulu",Kuusiston koulun pallokenttä,49.418682
86,235,Opastaulu,Frisbeegolfrata,Marjaniemi,Marjaniemi DiscGolfPark,22.918090
87,235,Opastaulu,Uimapaikka,Marjaniemi,Marjaniemen uimaranta ja sauna,129.555629
88,237,Opastaulu,Talviuintipaikka,Karunan Kallioranta,Kalliorannan talviuintipaikka,128.450111
89,237,Opastaulu,Pallokenttä,Karunan Kallioranta,Karunan jalkapallokenttä,171.623633
90,241,Opastaulu,Tenniskenttä,Piikkiön kehityksen pysäköintipaikka,Kehityksen kerhotalon tenniskenttä,105.644466
91,241,Opastaulu,Lentopallokenttä,Piikkiön kehityksen pysäköintipaikka,Kehityksen kerhotalon lentopallokenttä,130.732752
92,241,Opastaulu,Yleisurheilun harjoitusalue,Piikkiön kehityksen pysäköintipaikka,Kehityksen kerhotalon yleisurheilualue,131.430086
93,260,Pysakointialue,Tenniskenttä,Piikkiön kehityksen pysäköintialue,Kehityksen kerhotalon tenniskenttä,123.001569
94,260,Pysakointialue,Lentopallokenttä,Piikkiön kehityksen pysäköintialue,Kehityksen kerhotalon lentopallokenttä,148.083747
95,260,Pysakointialue,Yleisurheilun harjoitusalue,Piikkiön kehityksen pysäköintialue,Kehityksen kerhotalon yleisurheilualue,148.403236
96,268,Pysakointialue,Kuntosali,Paimion urheilupuisto,Kymppi-Sali,69.032725
97,268,Pysakointialue,Ulkokuntoilupaikka,Paimion urheilupuisto,Urheilupuiston ulkokuntoilupaikka,72.179811
98,268,Pysakointialue,Kilpajäähalli,Paimion urheilupuisto,Paimion jäähalli,80.309557
99,299,Tulipaikka,Frisbeegolfrata,Harvaluodon virkistysalue,Harvaluodon frisbeegolfrata,48.683796
100,299,Tulipaikka,Ulkokuntoilupaikka,Harvaluodon virkistysalue,Harvaluodon rannan ulkokuntoilulaite,56.716140
101,299,Tulipaikka,Uimaranta,Harvaluodon virkistysalue,Harvaluodon uimaranta,67.298834
102,302,Aktiviteetti,Frisbeegolfrata,NaN,Harvaluodon frisbeegolfrata,33.391335
103,302,Aktiviteetti,Ulkokuntoilupaikka,NaN,Harvaluodon rannan ulkokuntoilulaite,130.425985
104,302,Aktiviteetti,Uimaranta,NaN,Harvaluodon uimaranta,135.184795
105,307,Aktiviteetti,Pyöräilyalue,BMX -rata,Empon Bmx-rata,36.399955
106,307,Aktiviteetti,Pallokenttä,BMX -rata,Empon pallokenttä,84.556005
107,307,Aktiviteetti,Skeitti-/rullaluistelupaikka,BMX -rata,Empon skeittiparkki,88.654895
108,309,Vesillelasku,Uimaranta,NaN,Littoisten uimaranta,68.414472
109,309,Vesillelasku,Ulkokuntoilupaikka,NaN,Littoisten uimarannan ulkokuntoilulaitteet,123.585027
110,316,Polttopuuvarasto,Tenniskenttä,NaN,Kehityksen kerhotalon tenniskenttä,111.329744
111,316,Polttopuuvarasto,Yleisurheilun harjoitusalue,NaN,Kehityksen kerhotalon yleisurheilualue,134.029462
112,316,Polttopuuvarasto,Lentopallokenttä,NaN,Kehityksen kerhotalon lentopallokenttä,136.087777
113,317,Kierratys,Tenniskenttä,NaN,Kehityksen kerhotalon tenniskenttä,102.339512
114,317,Kierratys,Lentopallokenttä,NaN,Kehityksen kerhotalon lentopallokenttä,127.346135
115,317,Kierratys,Yleisurheilun harjoitusalue,NaN,Kehityksen kerhotalon yleisurheilualue,130.936932
116,321,Nahtavyys,Luistelukenttä,Huttalanmäen rautakautinen kalmisto,Piikkiön liikuntahallin luistelukenttä,177.532742
117,321,Nahtavyys,Pallokenttä,Huttalanmäen rautakautinen kalmisto,Piikkiön liikuntahallin pallokenttä,187.235021
118,321,Nahtavyys,Yleisurheilun harjoitusalue,Huttalanmäen rautakautinen kalmisto,Piikkiön liikuntahallin kenttä,188.014619
119,322,Luonnonnahtavyys,Yleisurheilun harjoitusalue,Perinnemaisema kohde,Piikkiön liikuntahallin kenttä,109.434351
120,322,Luonnonnahtavyys,Pallokenttä,Perinnemaisema kohde,Piikkiön liikuntahallin pallokenttä,120.928620
121,322,Luonnonnahtavyys,Luistelukenttä,Perinnemaisema kohde,Piikkiön liikuntahallin luistelukenttä,147.595724
122,335,Kahvila,Ulkokuntoilupaikka,NaN,Ilmaristen ulkokuntosali,117.937272
123,335,Kahvila,Tenniskenttä,NaN,Ilmaristen tenniskenttä,160.254531
124,335,Kahvila,Luistelukenttä,NaN,Ilmaristen koulun luistelukenttä,179.416736
125,6,Tulipaikka,"Laavu, kota tai kammi",Kota,Hamppukota,6.021374
126,9,Portaat,Luontotorni,Portaat,Nautelan lintutorni,19.049639
127,19,Opastaulu,Beachvolley-/rantalentopallokenttä,Tammireittien opastaulu,Littoisten beachvolleykenttä,139.097078
128,29,Nahtavyys,Beachvolley-/rantalentopallokenttä,Littoisten verkatehdas,Littoisten beachvolleykenttä,196.010647
129,40,Nahtavyys,Ulkokuntoilupaikka,Pyhän Pietarin kirkko,Kaupungintalon ulkokuntosali,73.736674
130,92,Opastaulu,Talviuintipaikka,Paimion kotiseutumuseo,Oinilan maauimalan talviuintipaikka,153.851340
131,93,Opastaulu,Talviuintipaikka,Muurahaispolku,Oinilan maauimalan talviuintipaikka,166.014561
132,96,Pysakointialue,Talviuintipaikka,Kotiseutumuseo ja Muurahaispolku,Oinilan maauimalan talviuintipaikka,195.013707
133,100,Kahvila,Kuntokeskus,Cafe Asta,Voimakas Sali,140.199278
134,101,Kahvila,Kuntokeskus,R-kioski,Voimakas Sali,135.778550
135,115,Kahvila,Kuntokeskus,Heimon grilli,Voimakas Sali,199.771906
136,120,Opastaulu,Hiihtotunneli,Hiihtoputki Finnfoam Paippi,Hiihtotunneli Paippi,15.778271
137,143,Aktiviteetti,Ulkokuntoilupaikka,Liikenne- ja leikkipuisto,Hovirinnan rantapuiston ulkokuntoilulaitteet,92.632174
138,150,Nahtavyys,Liikuntasali,Tuorlan kartano,Ammattiopisto Livian liikuntasali,7.235763
139,151,Pysakointialue,Liikuntasali,Tuorlan pysäköintialue,Ammattiopisto Livian liikuntasali,61.051031
140,152,Opastaulu,Liikuntasali,Ammattiopisto Livia,Ammattiopisto Livian liikuntasali,77.135462
141,159,Nahtavyys,Tanssi-/ryhmäliikuntatila,Piikkiön kirkko,Tanssistudio Point,160.412823
142,183,Pysakointialue,Uimapaikka,Sarapiston pysäköintialue,Sarapiston uimapaikka,198.314988
143,191,Nahtavyys,Uimaranta,Sauvon Kädet ry kesänäyttely,Rantolan uimaranta,81.053931
144,194,Nahtavyys,Lähiliikuntapaikka,Sauvon kirkko,Palvelukeskuksen lähiliikuntapaikka,153.052156
145,195,Nahtavyys,Lähiliikuntapaikka,Sauvon tori,Palvelukeskuksen lähiliikuntapaikka,185.358640
146,218,Opastaulu,Frisbeegolfrata,Nunnan luontopolku,Nunnan frisbeegolfrata,18.250414
147,227,Opastaulu,Liikuntasali,Tuorla,Ammattiopisto Livian liikuntasali,76.769886
148,233,Opastaulu,Uimaranta,Rantola,Rantolan uimaranta,143.955834
149,234,Opastaulu,Lähiliikuntapaikka,NaN,Palvelukeskuksen lähiliikuntapaikka,182.280516
150,236,Opastaulu,Uimapaikka,Sarapisto,Sarapiston uimapaikka,28.203200
151,239,Opastaulu,Luontotorni,Maalun pirunpellonpolku,Maalun näköalatorni,107.984253
152,243,Kahvila,Liikuntasali,Tuorlan majatalo,Ammattiopisto Livian liikuntasali,106.186654
153,244,Nahtavyys,Kuntosali,Sauvon kotiseutumuseo,Sauvon kunnan omatoimikuntosali,137.738904
154,245,Kahvila,Kuntosali,Kesäkahvila,Sauvon kunnan omatoimikuntosali,145.117139
155,247,Tilamyynti,Ratsastuskenttä,Hännilän tila,Hännilän Tilan ratsastuskenttä,140.073717
156,248,Kahvila,Uimaranta,Rantolan puoti,Rantolan uimaranta,169.503679
157,250,Majoitus,Talviuintipaikka,Villa Volax,Villa Wolaxin talviuintipaikka,109.614375
158,257,Nahtavyys,Hiihtotunneli,"Finnfoam paippi, hiihtoputki",Hiihtotunneli Paippi,8.167670
159,262,Pysakointialue,Frisbeegolfrata,Nunnan pysäköintialue,Nunnan frisbeegolfrata,18.585137
160,264,Pysakointialue,Luontotorni,Maalun pysäköintialue,Maalun näköalatorni,117.555099
161,265,Pysakointialue,Lähiliikuntapaikka,Sauvon kirkon pysäköintialue,Palvelukeskuksen lähiliikuntapaikka,142.504003
162,273,Polttopuuvarasto,Luontotorni,Polttopuuvarasto,Vaarniemen näkötorni,156.946875
163,274,Tulipaikka,Luontotorni,Laavu,Vaarniemen näkötorni,73.945878
164,280,Kuivakaymala,Luontotorni,NaN,Vaarniemen näkötorni,61.809160
165,292,Portaat,Luontotorni,Portaat,Vaarniemen näkötorni,140.116438
166,295,Vesillelasku,Uimapaikka,NaN,Kuuslahden uimaranta,4.635047
167,303,Vesillelasku,Uimapaikka,NaN,Raadelman uimapaikka,6.756248
168,313,Aktiviteetti,Frisbeegolfrata,NaN,Nunnan frisbeegolfrata,26.863980
169,315,Tulipaikka,Frisbeegolfrata,NaN,Nunnan frisbeegolfrata,38.351572
170,334,Nakoala,Luontotorni,NaN,Maalun näköalatorni,6.396462

In [252]:
# Move rows from needs_checking to true matches

# Row indexes to be moved
row_idxs_to_true = [54, 102, 105, 158, 168, 170]

# Get the rows from the original dataframe
rows_to_move = needs_checking.loc[row_idxs_to_true]

# Concatenate the rows to the correct dataframe
true_matches = pd.concat([true_matches, rows_to_move], ignore_index=True)

# Drop from the original dataframe
needs_checking = needs_checking.drop(index=row_idxs_to_true)

In [253]:
# When you are sure of your mismatching rows you can add them to the not_matched df
# to represent that a valid match was not found for the entry

not_matched = pd.concat([not_matched, mismatches], axis=0, ignore_index=True)
not_matched = pd.concat([not_matched, needs_checking], axis=0, ignore_index=True)
not_matched = pd.concat([not_matched, review_mismatches_duplicates], axis=0, ignore_index=True)
not_matched = pd.concat([not_matched, true_matches_duplicates], axis=0, ignore_index=True)

In [254]:
# Then you can mark the columns as nan to represent that a match was not found

not_matched[[LIPAS_ID_COL,TYPE_COL_LIPAS, NAME2_COL, 'mapped_lipas_category', 'category_match']] = np.nan
not_matched.head()

,fid,omistaja,yllapitaja,tyyppi,lisatieto,kunta,reitti,kohde,sijainti,palvelut,...,lipas_tyyppi_nimi_fi,lipas_nimi_fi,n,distance,feature_x,feature_y,nearest_x,nearest_y,mapped_lipas_category,category_match
0,1,Muu,Yksityinen / yhdistys,Pysakointi_liikeste,NaN,Kaarina,Tuorlan esteetön luontopolku,Pysäköintialue,Avaruuspuisto Väisälä,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3,NaN,NaN,Taukopaikka,NaN,Lieto,Ankka-Nautela luontopolku,Taukopaikka,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4,NaN,NaN,Portaat,NaN,Lieto,Vanhalinnan Ystävänpolku,Portaat,Vanhalinna,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5,NaN,NaN,Tulipaikka,NaN,Lieto,Ankka-Nautela luontopolku,Laavu,Liesan maja,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,9,NaN,NaN,Taukopaikka,Katettu eväspöytä ja penkit,Lieto,Ankka-Nautela luontopolku,Taukopaikka,Poso,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [255]:
# After you have reviewed the results and are sure of your matches and mismatches you can make the final matching df

final_matching_df =  pd.concat([not_matched, true_matches], axis=0, ignore_index=True)
final_matching_df

,fid,omistaja,yllapitaja,tyyppi,lisatieto,kunta,reitti,kohde,sijainti,palvelut,...,lipas_tyyppi_nimi_fi,lipas_nimi_fi,n,distance,feature_x,feature_y,nearest_x,nearest_y,mapped_lipas_category,category_match
0,1,Muu,Yksityinen / yhdistys,Pysakointi_liikeste,NaN,Kaarina,Tuorlan esteetön luontopolku,Pysäköintialue,Avaruuspuisto Väisälä,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3,NaN,NaN,Taukopaikka,NaN,Lieto,Ankka-Nautela luontopolku,Taukopaikka,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4,NaN,NaN,Portaat,NaN,Lieto,Vanhalinnan Ystävänpolku,Portaat,Vanhalinna,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5,NaN,NaN,Tulipaikka,NaN,Lieto,Ankka-Nautela luontopolku,Laavu,Liesan maja,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,9,NaN,NaN,Taukopaikka,Katettu eväspöytä ja penkit,Lieto,Ankka-Nautela luontopolku,Taukopaikka,Poso,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
431,401,Kunta,Kunta / liikuntatoimi,Aktiviteetti,Frisbeegolfrata,Kaarina,NaN,NaN,NaN,NaN,...,Frisbeegolfrata,Harvaluodon frisbeegolfrata,1.0,33.391335,252683.858454,6.701073e+06,252705.8815,6.701098e+06,NaN,False
432,410,Kunta,Kunta / muu,Aktiviteetti,NaN,Kaarina,NaN,BMX -rata,NaN,NaN,...,Pyöräilyalue,Empon Bmx-rata,1.0,36.399955,245994.628050,6.703913e+06,245978.5000,6.703881e+06,NaN,False
433,345,Muu,NaN,Nahtavyys,NaN,Paimio,NaN,"Finnfoam paippi, hiihtoputki",NaN,NaN,...,Hiihtotunneli,Hiihtotunneli Paippi,1.0,8.167670,264290.939567,6.706426e+06,264299.1058,6.706426e+06,NaN,False
434,422,Kunta,Kunta / muu,Aktiviteetti,Nunnan frisbeegolfrata,Kaarina,NaN,NaN,NaN,NaN,...,Frisbeegolfrata,Nunnan frisbeegolfrata,1.0,26.863980,248978.598373,6.709952e+06,249003.1898,6.709941e+06,NaN,False
435,451,Muu,Yksityinen / yhdistys,Nakoala,Maalun näköalatorni,Sauvo,NaN,NaN,NaN,NaN,...,Luontotorni,Maalun näköalatorni,1.0,6.396462,256984.091010,6.688060e+06,256985.0838,6.688054e+06,NaN,False

In [256]:
# Then you can take a subset of columns of the final matching so it is easy to use with a database table for example
# Here is your dataset identificator column and the matched Lipas entry's identificator column

final_matching_df = final_matching_df[[ID_COL, LIPAS_ID_COL]].copy()
final_matching_df

     source_id  lipas_id
0            1       NaN
1            3       NaN
2            4       NaN
3            5       NaN
4            8       NaN
..         ...       ...
431        302  612639.0
432        307  604689.0
433        257   98159.0
434        313  529979.0
435        334  616945.0

[436 rows x 2 columns]

In [257]:
final_matching_df[[ID_COL, LIPAS_ID_COL]] = final_matching_df[[ID_COL, LIPAS_ID_COL]].astype("Int64")
final_matching_df.dtypes

source_id    Int64
lipas_id     Int64
dtype: object

In [258]:
# Those can be renamed for clarity if wished

final_matching_df.rename(columns={LIPAS_ID_COL: "mapped_lipas_id", ID_COL: "my_id"}, inplace=True)
final_matching_df

     my_id  mapped_lipas_id
0        1             <NA>
1        3             <NA>
2        4             <NA>
3        5             <NA>
4        8             <NA>
..     ...              ...
431    302           612639
432    307           604689
433    257            98159
434    313           529979
435    334           616945

[436 rows x 2 columns]

In [259]:
# Let's fill the nans as 0 because in our data model 0 represents no match found

final_matching_df["mapped_lipas_id"] = final_matching_df["mapped_lipas_id"].fillna(0)
final_matching_df

     my_id  mapped_lipas_id
0        1                0
1        3                0
2        4                0
3        5                0
4        8                0
..     ...              ...
431    302           612639
432    307           604689
433    257            98159
434    313           529979
435    334           616945

[436 rows x 2 columns]

In [260]:
# Drop extra rows that have resulted from the spatial distance search, these should all be mapped to 0

final_matching_df = final_matching_df.sort_values(by=["my_id", "mapped_lipas_id"],ascending=[True, False])
final_matching_df = final_matching_df.drop_duplicates(subset="my_id",keep="first").reset_index(drop=True)

In [261]:
# Sanity check

print(f"Found duplicates: {(final_matching_df["mapped_lipas_id"] > 0).sum()}")
print(f"Number of unique ids: {final_matching_df['my_id'].nunique()}")
print(f"All ids unique: {final_matching_df['my_id'].is_unique}")

Found duplicates: 26
Number of unique ids: 347
All ids unique: True

In [262]:
# Then you can save results to your device if wanted

final_matching_df.to_csv("final_matching_df2.csv", index=False)